import "./globals.css";

import type { Metadata } from "next";
import { pretendard } from "@repo/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      suppressHydrationWarning
      className={`${pretendard.variable} font-pretendard`}
    >
      <body>{children}</body>
    </html>
  );
}
